### ISSUE TITLE
Robotiq 140 Gripper bends awkwardly

### ISSUE THREAD

**Issue by luarss** [ARISE-Initiative/robosuite#278] opened 2022-01-07 06:17 UTC
When I attempt to run a modified version of the test_robotiq_140.py code (directory: ./tests/test_grippers/) there was weird bending of the gripper around the box object as seen in the picture attached. Any suggestions as to why there is such a bending?

Thanks!
![image](https://user-images.githubusercontent.com/39641663/148500742-c61cc1c8-dff0-4246-897c-8befc38b640e.png)

**Comment by cremebrule** [comment] 2022-01-08 22:55
Hi @luarss ,

Yes, this is expected behavior. This is because the joints that are a part of the Robotiq 140 gripper are actually tendons instead of the traditional joints. This means that, depending on the magnitude and location of the specific contacts on the fingertip, the gripper may bend in different ways.

When I had originally imported this gripper, I had to spend a lot of time tuning it to function somewhat normally. It's still not perfect under all circumstances. Feel free to try tuning it further (e.g.: tuning the values [HERE](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/models/assets/grippers/robotiq_gripper_140.xml#L17)), and if find another set of parameters perform better, feel free to open another issue and / or a PR!

Closing this issue for now, feel free to re-open if you have further issues.

**Closed by cremebrule** 2022-01-08 22:55 UTC
